// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyetlgqbgxbppztihbfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZXRsZ3FiZ3hicHB6dGloYmZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTQ4MzQsImV4cCI6MjA2Mzg5MDgzNH0.isUh0UKcrvGBsqLIupFuoCYU2s2fIjItSVTZNitzCyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);